package engine

import "pokearena/internal/domain"

// --- Fling and Natural Gift data ---
//
// These two tables are behavior, not catalog identity, so they live with the
// moves rather than in data/items.json — same line the registry draws.
// Generated from Showdown's data/items.ts and checked against the catalog:
// TestFlingAndNaturalGiftCoverTheCatalog fails if an item is added without a
// Fling power, or a berry without a Natural Gift entry.
//
// One deliberate departure from that source. Showdown declares no `fling` block
// on any berry, in the current data file or in the gen5/7/8 mods, and its Fling
// implementation does `if (!item.fling) return false` — which taken literally
// would make Fling fail on all 46 of our berries. Every other reference says
// berries Fling at 10 base power and the target eats the thrown berry, and
// Showdown's own Fling code carries an `if (item.isBerry)` branch that would be
// unreachable otherwise. Berries are entered here at 10.
//
// The plates are the same gap and get the same treatment. Showdown declares no
// `fling` block on any of the seventeen either — not in data/items.ts, not in
// the gen4 or champions mods — so a literal reading makes Fling fail on all of
// them. Every other reference puts a Plate at 90, the tier Grip Claw and Thick
// Club already sit in here, and they are entered at 90. Sea Incense, by
// contrast, does carry upstream data, at 10.

var flingPower = map[ItemKind]int{
	ItemIronBall:  130,
	ItemHardStone: 100,
	ItemGripClaw:  90,
	ItemThickClub: 90,
	// The plates, all at the same tier — see the note above on why they are
	// entered by hand rather than read off upstream.
	ItemDracoPlate:  90,
	ItemDreadPlate:  90,
	ItemEarthPlate:  90,
	ItemFistPlate:   90,
	ItemFlamePlate:  90,
	ItemIciclePlate: 90,
	ItemInsectPlate: 90,
	ItemIronPlate:   90,
	ItemMeadowPlate: 90,
	ItemMindPlate:   90,
	ItemPixiePlate:  90,
	ItemSkyPlate:    90,
	ItemSplashPlate: 90,
	ItemSpookyPlate: 90,
	ItemStonePlate:  90,
	ItemToxicPlate:  90,
	ItemZapPlate:    90,
	ItemSeaIncense:  10,

	// Ability Shield.
	ItemAbilityShield: 30,

	ItemAdrenalineOrb: 30,

	// Mail carries no upstream fling value because it refuses to be flung at
	// all — the entry keeps TestFlingAndNaturalGiftCoverTheCatalog satisfied
	// and is never read, since mailRefusesRemovalBy returns first.
	ItemMail: 10,

	// The terrain seeds and Room Service.
	ItemElectricSeed: 10,
	ItemGrassySeed:   10,
	ItemMistySeed:    10,
	ItemPsychicSeed:  10,
	ItemRoomService:  100,
	ItemMirrorHerb:   30,

	// The force-switch items.
	ItemEjectButton:     30,
	ItemEjectPack:       50,
	ItemRedCard:         10,
	ItemAssaultVest:     80,
	ItemBlunderPolicy:   80,
	ItemHeavyDutyBoots:  80,
	ItemQuickClaw:       80,
	ItemRazorClaw:       80,
	ItemSafetyGoggles:   80,
	ItemStickyBarb:      80,
	ItemWeaknessPolicy:  80,
	ItemDragonFang:      70,
	ItemPoisonBarb:      70,
	ItemDampRock:        60,
	ItemHeatRock:        60,
	ItemLeek:            60,
	ItemRockyHelmet:     60,
	ItemTerrainExtender: 60,
	ItemUtilityUmbrella: 60,
	ItemSharpBeak:       50,
	ItemIcyRock:         40,
	ItemLuckyPunch:      40,
	ItemAbsorbBulb:      30,
	ItemBerryJuice:      30,
	ItemBindingBand:     30,
	ItemBlackBelt:       30,
	ItemBlackGlasses:    30,
	ItemBlackSludge:     30,
	ItemCellBattery:     30,
	ItemCharcoal:        30,
	ItemClearAmulet:     30,
	ItemCovertCloak:     30,
	ItemFlameOrb:        30,
	ItemKingsRock:       30,
	ItemLifeOrb:         30,
	ItemLightClay:       30,
	ItemLoadedDice:      30,
	ItemLuminousMoss:    30,
	ItemMagnet:          30,
	ItemMetalCoat:       30,
	ItemMetronome:       30,
	ItemMiracleSeed:     30,
	ItemMysticWater:     30,
	ItemNeverMeltIce:    30,
	ItemProtectivePads:  30,
	ItemPunchingGlove:   30,
	ItemRazorFang:       30,
	ItemScopeLens:       30,
	ItemShellBell:       30,
	ItemSnowball:        30,
	ItemSpellTag:        30,
	ItemThroatSpray:     30,
	ItemToxicOrb:        30,
	ItemTwistedSpoon:    30,
	ItemAguavBerry:      10,
	ItemAirBalloon:      10,
	ItemApicotBerry:     10,
	ItemAspearBerry:     10,
	ItemBabiriBerry:     10,
	ItemBigRoot:         10,
	ItemBrightPowder:    10,
	ItemChartiBerry:     10,
	ItemCheriBerry:      10,
	ItemChestoBerry:     10,
	ItemChilanBerry:     10,
	ItemChoiceBand:      10,
	ItemChoiceScarf:     10,
	ItemChoiceSpecs:     10,
	ItemChopleBerry:     10,
	ItemCobaBerry:       10,
	ItemColburBerry:     10,
	ItemCustapBerry:     10,
	ItemEnigmaBerry:     10,
	ItemExpertBelt:      10,
	ItemFairyFeather:    10,
	ItemFigyBerry:       10,
	ItemFocusBand:       10,
	ItemFocusSash:       10,
	ItemFullIncense:     10,
	ItemGanlonBerry:     10,
	ItemHabanBerry:      10,
	ItemIapapaBerry:     10,
	ItemJabocaBerry:     10,
	ItemKasibBerry:      10,
	ItemKebiaBerry:      10,
	ItemKeeBerry:        10,
	ItemLaggingTail:     10,
	ItemLaxIncense:      10,
	ItemLeftovers:       10,
	ItemLeppaBerry:      10,
	ItemLiechiBerry:     10,
	ItemLumBerry:        10,
	ItemMagoBerry:       10,
	ItemMarangaBerry:    10,
	ItemMentalHerb:      10,
	ItemMicleBerry:      10,
	ItemMuscleBand:      10,
	ItemOccaBerry:       10,
	ItemOranBerry:       10,
	ItemPasshoBerry:     10,
	ItemPayapaBerry:     10,
	ItemPechaBerry:      10,
	ItemPersimBerry:     10,
	ItemPetayaBerry:     10,
	ItemPowerHerb:       10,
	ItemRawstBerry:      10,
	ItemRindoBerry:      10,
	ItemRingTarget:      10,
	ItemRoseliBerry:     10,
	ItemRowapBerry:      10,
	ItemSalacBerry:      10,
	ItemShedShell:       10,
	ItemShucaBerry:      10,
	ItemSilkScarf:       10,
	ItemSilverPowder:    10,
	ItemSitrusBerry:     10,
	ItemSmoothRock:      10,
	ItemSoftSand:        10,
	ItemStarfBerry:      10,
	ItemTangaBerry:      10,
	ItemWacanBerry:      10,
	ItemWhiteHerb:       10,
	ItemWideLens:        10,
	ItemWikiBerry:       10,
	ItemWiseGlasses:     10,
	ItemYacheBerry:      10,
	ItemZoomLens:        10,
}

var naturalGift = map[ItemKind]struct {
	Type  domain.Type
	Power int
}{
	ItemAguavBerry:   {"dragon", 80},
	ItemApicotBerry:  {"ground", 100},
	ItemAspearBerry:  {"ice", 80},
	ItemBabiriBerry:  {"steel", 80},
	ItemChartiBerry:  {"rock", 80},
	ItemCheriBerry:   {"fire", 80},
	ItemChestoBerry:  {"water", 80},
	ItemChilanBerry:  {"normal", 80},
	ItemChopleBerry:  {"fighting", 80},
	ItemCobaBerry:    {"flying", 80},
	ItemColburBerry:  {"dark", 80},
	ItemCustapBerry:  {"ghost", 100},
	ItemEnigmaBerry:  {"bug", 100},
	ItemFigyBerry:    {"bug", 80},
	ItemGanlonBerry:  {"ice", 100},
	ItemHabanBerry:   {"dragon", 80},
	ItemIapapaBerry:  {"dark", 80},
	ItemJabocaBerry:  {"dragon", 100},
	ItemKasibBerry:   {"ghost", 80},
	ItemKebiaBerry:   {"poison", 80},
	ItemKeeBerry:     {"fairy", 100},
	ItemLeppaBerry:   {"fighting", 80},
	ItemLiechiBerry:  {"grass", 100},
	ItemLumBerry:     {"flying", 80},
	ItemMagoBerry:    {"ghost", 80},
	ItemMarangaBerry: {"dark", 100},
	ItemMicleBerry:   {"rock", 100},
	ItemOccaBerry:    {"fire", 80},
	ItemOranBerry:    {"poison", 80},
	ItemPasshoBerry:  {"water", 80},
	ItemPayapaBerry:  {"psychic", 80},
	ItemPechaBerry:   {"electric", 80},
	ItemPersimBerry:  {"ground", 80},
	ItemPetayaBerry:  {"poison", 100},
	ItemRawstBerry:   {"grass", 80},
	ItemRindoBerry:   {"grass", 80},
	ItemRoseliBerry:  {"fairy", 80},
	ItemRowapBerry:   {"dark", 100},
	ItemSalacBerry:   {"fighting", 100},
	ItemShucaBerry:   {"ground", 80},
	ItemSitrusBerry:  {"psychic", 80},
	ItemStarfBerry:   {"psychic", 100},
	ItemTangaBerry:   {"bug", 80},
	ItemWacanBerry:   {"electric", 80},
	ItemWikiBerry:    {"rock", 80},
	ItemYacheBerry:   {"ice", 80},
}
