//go:build showdown

package showdown

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"sync"
	"testing"
)

// gaps_test.go is the ledger: what this engine is currently known not to do,
// stated one upstream case at a time.
//
// The suite is expected to be red, which is a useless thing to say unless
// somebody writes down *how* red and keeps the number honest. So every case
// has an entry here or it is expected to pass, and the runner treats a
// disagreement in either direction as a failure:
//
//	ledger says pass, case passes    →  quiet
//	ledger says pass, case fails     →  FAIL — a regression, or a new port
//	                                    that needs triaging into the ledger
//	ledger has a gap, case fails     →  quiet, counted, reason reported
//	ledger has a gap, case passes    →  FAIL — the gap closed and the entry
//	                                    is now hiding whatever breaks next
//
// The last row is the one that makes this worth maintaining. A quarantine
// list that is never pruned rots into a list of tests nobody runs; a
// quarantine list that fails when an entry goes stale prunes itself.
//
// Keys are "<upstream describe>: <upstream it>", which is stable across
// renames of the Go function and greppable against the JS.

// gapKind classifies why a case does not pass, because the three kinds want
// completely different follow-up.
type gapKind string

const (
	// gapBug: the engine is wrong and should be fixed. These are the
	// findings — the reason the port exists.
	gapBug gapKind = "bug"
	// gapMissing: the mechanic is not implemented at all. A feature request,
	// not a defect.
	gapMissing gapKind = "missing"
	// gapScope: this engine deliberately does not model the thing — a
	// singles-only engine has no ally, an 80-species dex has no Ditto. The
	// case is kept so the decision stays visible and so it starts passing if
	// the scope ever widens.
	gapScope gapKind = "scope"
	// gapPort: the translation itself is suspect and needs a second look.
	// Entries should not survive triage; anything still here is work in
	// progress.
	gapPort gapKind = "port"
)

// gap is one ledger row.
type gap struct {
	Kind gapKind
	// Why states what is actually wrong, in enough detail that somebody can
	// pick the row up without re-deriving the diagnosis. "not implemented" is
	// not enough; "Transform has no dataset entry, and copying a species would
	// need a forme layer the Pokemon struct does not have" is.
	Why string
}

// gaps is the ledger. It is generated by triage and edited by hand; see
// docs/showdown-port.md for the workflow.
//
// It starts empty on purpose. An empty ledger against a freshly ported corpus
// means every case is claimed to pass, which is false — the first full run is
// what turns that claim into the real list.
var gaps = map[string]gap{}

// --- reconciliation -----------------------------------------------------

type outcome struct {
	Key    string   `json:"key"`
	Status string   `json:"status"` // pass | gap | skip | regress | stale
	Kind   string   `json:"kind,omitempty"`
	Why    string   `json:"why,omitempty"`
	Detail []string `json:"detail,omitempty"`
}

var (
	tally   []outcome
	tallyMu sync.Mutex
)

func recordOutcome(o outcome) {
	tallyMu.Lock()
	tally = append(tally, o)
	tallyMu.Unlock()
}

// verdict is the slice of *testing.T that reconcile needs. It exists so the
// harness self-test can watch reconcile decide without having to make a real
// sub-test fail — see TestReconcileDecidesCorrectly.
type verdict interface {
	Helper()
	Errorf(format string, args ...any)
	Skipf(format string, args ...any)
}

// reconcile compares one case's real outcome against the ledger and decides
// whether the Go test fails.
func reconcile(t verdict, key string, fails []string, skip string) {
	t.Helper()
	if skip != "" {
		recordOutcome(outcome{Key: key, Status: "skip", Why: skip})
		t.Skipf("out of scope: %s", skip)
		return
	}
	g, listed := gaps[key]
	switch {
	case listed && len(fails) > 0:
		recordOutcome(outcome{Key: key, Status: "gap", Kind: string(g.Kind), Why: g.Why, Detail: fails})
		t.Skipf("known %s: %s\n%s", g.Kind, g.Why, strings.Join(fails, "\n"))
	case listed && len(fails) == 0:
		recordOutcome(outcome{Key: key, Status: "stale", Kind: string(g.Kind), Why: g.Why})
		t.Errorf("this case passes now, but the ledger still lists it as a known %s:\n    %s\n\n"+
			"Delete the %q entry from gaps in gaps_test.go. Leaving it there means the\n"+
			"next thing that breaks this case will be reported as expected.", g.Kind, g.Why, key)
	case !listed && len(fails) > 0:
		recordOutcome(outcome{Key: key, Status: "regress", Detail: fails})
		t.Errorf("%s\n\nIf this is a newly ported case rather than a regression, triage it and\n"+
			"add a row to gaps in gaps_test.go keyed %q.", strings.Join(fails, "\n"), key)
	default:
		recordOutcome(outcome{Key: key, Status: "pass"})
	}
}

// --- the report ---------------------------------------------------------

// TestMain prints the tally after the run, and writes the machine-readable
// form when PS_REPORT names a file. The summary is the deliverable of a red
// suite: "1,190 of 1,977 pass, 340 are known bugs, 190 unimplemented, 257 out
// of scope" is a statement about the engine. A wall of FAIL lines is not.
func TestMain(m *testing.M) {
	code := m.Run()
	summarise()
	if path := os.Getenv("PS_REPORT"); path != "" {
		writeReport(path)
	}
	os.Exit(code)
}

func summarise() {
	tallyMu.Lock()
	defer tallyMu.Unlock()
	if len(tally) == 0 {
		return
	}
	counts := map[string]int{}
	byKind := map[string]int{}
	skipReasons := map[string]int{}
	for _, o := range tally {
		counts[o.Status]++
		if o.Status == "gap" {
			byKind[o.Kind]++
		}
		if o.Status == "skip" {
			skipReasons[o.Why]++
		}
	}
	total := len(tally)
	fmt.Fprintf(os.Stderr, "\n──── Showdown port ────────────────────────────────────────\n")
	fmt.Fprintf(os.Stderr, "  %4d cases ported\n", total)
	fmt.Fprintf(os.Stderr, "  %4d pass          (%.0f%% of the cases this engine attempts)\n",
		counts["pass"], pct(counts["pass"], total-counts["skip"]))
	fmt.Fprintf(os.Stderr, "  %4d known gaps\n", counts["gap"])
	for _, k := range []string{string(gapBug), string(gapMissing), string(gapScope), string(gapPort)} {
		if byKind[k] > 0 {
			fmt.Fprintf(os.Stderr, "         %4d %s\n", byKind[k], k)
		}
	}
	fmt.Fprintf(os.Stderr, "  %4d not attempted\n", counts["skip"])
	for _, r := range topReasons(skipReasons, 6) {
		fmt.Fprintf(os.Stderr, "         %4d %s\n", skipReasons[r], r)
	}
	if counts["regress"] > 0 {
		fmt.Fprintf(os.Stderr, "  %4d UNTRIAGED OR REGRESSED — see the failures above\n", counts["regress"])
	}
	if counts["stale"] > 0 {
		fmt.Fprintf(os.Stderr, "  %4d STALE LEDGER ENTRIES — these pass now; delete their rows\n", counts["stale"])
	}
	fmt.Fprintf(os.Stderr, "───────────────────────────────────────────────────────────\n\n")
}

func pct(n, d int) float64 {
	if d == 0 {
		return 0
	}
	return 100 * float64(n) / float64(d)
}

func topReasons(m map[string]int, n int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if m[keys[i]] != m[keys[j]] {
			return m[keys[i]] > m[keys[j]]
		}
		return keys[i] < keys[j]
	})
	if len(keys) > n {
		keys = keys[:n]
	}
	return keys
}

func writeReport(path string) {
	tallyMu.Lock()
	defer tallyMu.Unlock()
	sort.Slice(tally, func(i, j int) bool { return tally[i].Key < tally[j].Key })
	b, err := json.MarshalIndent(tally, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "showdown port: could not encode the report: %v\n", err)
		return
	}
	if err := os.WriteFile(path, b, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "showdown port: could not write %s: %v\n", path, err)
	}
}
